enum AuthActions {
    EDIT_USER_INFO = "EDIT_USER_INFO",
    LOGIN_USER = "LOGIN_USER",
    SET_CURRENT_USER = "SET_CURRENT_USER",
    LOGOUT = "LOGOUT_USER",
    FOLLOW_USER = "FOLLOW",
    UNFOLLOW_USER = "UNFOLLOW"
}

export default AuthActions;