enum PostsTypes {
    GET_USER_POSTS = "GET_USER_POSTS",
    MAKE_POST = "MAKE_USER_POST",
    EDIT_POST = "EDIT_USER_POST",
    EDIT_USER_INFO = "EDIT_USER",
    COMMENT_POST = "COMMENT_USER_POST",
    DELETE_COMMENT = "DELETE_USER_POST_COMMENT",
    RESET_POSTS = "RESET_USER_POSTS",
    SEARCH_POSTS = "SEARCH_USER_POSTS",
    DELETE_POST = "DELETE_USER_POST",
    GET_SUB_USERS_POSTS = "GET_SUB_USERS_POSTS",
    SET_USER_POSTS = "SET_USER_POSTS",
    COMMENT_FOUND_POST = "COMMENT_FOUND_POST",
    DELETE_COMMENT_FOUND_POST = "DELETE_COMMENT_FOUND_POST",
}

export default PostsTypes;